@TrackingSystem.API_HostAddress = http://localhost:5271
GET {{TrackingSystem.API_HostAddress}}/students
Accept: application/json

GET {{TrackingSystem.API_HostAddress}}/students/1
Accept: application/json

POST {{TrackingSystem.API_HostAddress}}/students
Content-Type: application/json

{
  "firstName": "Иван",
  "lastName": "Иванов",
  "middleName": "Иванович",
  "studentIdNumber": "ИТ-2024-001",
  "email": "ivanov@edu.ru",
  "phoneNumber": "+79991234567",
  "groupId": 1
}

